# SPDX-FileCopyrightText: 2018-2026 Stichting DuckDB Foundation
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: MIT AND Apache-2.0
#
# Modified by Vane contributors.

# ruff: noqa: F401
"""The public Python API for the Vane data engine.

Vane owns this package and its native extension.  The separately distributed
``duckdb`` package may be installed and imported in the same Python process;
the two distributions do not share Python modules or extension names.
"""

import importlib as _importlib
import typing as _typing

from vane._audio_file import (
    AudioFileError,
    AudioFileFormatError,
    AudioFileLimitError,
    AudioMetadata,
    audio_metadata,
    resample,
)
from vane._dbapi_type_object import (
    BINARY,
    DATETIME,
    NUMBER,
    ROWID,
    STRING,
    DBAPITypeObject,
)
from vane._env import EnvRegistry, env
from vane._expression_udf import attach_function, cls, detach_function, func
from vane._expressions import col, lit, sql_expr
from vane._file import (
    FileStat,
    VaneFileReader,
    audio_file,
    file,
    file_content_id,
    file_enrich,
    file_exists,
    file_locator_id,
    file_mime_type,
    file_path,
    file_same_content,
    file_same_location,
    file_size,
    file_stat,
    from_files,
    guess_mime_type,
    image_file,
    list_files,
    open_file,
    to_file,
    try_to_file,
    video_file,
)
from vane._image import (
    Image,
    ImageFormat,
    ImageMode,
    ImageProperty,
    image_attribute,
    image_channel,
    image_height,
    image_mode,
    image_to_tensor,
    image_width,
)
from vane._image_file import (
    ImageFileError,
    ImageFileFormatError,
    ImageFileLimitError,
    ImageMetadata,
    decode_image_file,
    image_file_metadata,
)
from vane._image_operators import convert_image, crop, decode_image, encode_image, image_hash, resize
from vane._read_video_frames import read_video_frames
from vane._video_expressions import (
    build_video_index,
    get_video_frame_by_idx,
    video_frames,
    video_index_info,
    video_keyframes,
    video_scan_stats,
)
from vane._video_file import (
    VideoFileError,
    VideoFileFormatError,
    VideoFileLimitError,
    VideoFrameData,
    VideoMetadata,
    video_metadata,
)

if _typing.TYPE_CHECKING:
    from vane import ai as ai
    from vane import runners as runners
    from vane import sqltypes as sqltypes
    from vane import udf as udf
    from vane.runners.runner import Runner as _Runner
else:
    _Runner = _typing.Any
from vane._native import (
    AudioFile,
    BinderException,
    CaseExpression,
    CatalogException,
    CoalesceOperator,
    ColumnExpression,
    ConnectionException,
    ConstantExpression,
    ConstraintException,
    ConversionException,
    CSVLineTerminator,
    DatabaseError,
    DataError,
    DefaultExpression,
    DependencyException,
    DuckDBPyConnection,
    DuckDBPyRelation,
    Error,
    ExpectedResultType,
    ExplainType,
    Expression,
    FatalException,
    File,
    FunctionExpression,
    HTTPException,
    ImageFile,
    IntegrityError,
    InternalError,
    InternalException,
    InterruptException,
    InvalidInputException,
    InvalidTypeException,
    IOException,
    LambdaExpression,
    MediaType,
    NotImplementedException,
    NotSupportedError,
    OperationalError,
    OutOfMemoryException,
    OutOfRangeException,
    ParserException,
    PermissionException,
    ProgrammingError,
    PythonExceptionHandling,
    RenderMode,
    SequenceException,
    SerializationException,
    SQLExpression,
    StarExpression,
    Statement,
    StatementType,
    SyntaxException,
    TransactionException,
    TypeMismatchException,
    VideoFile,
    Warning,
    __formatted_python_version__,
    __git_revision__,
    __interactive__,
    __jupyter__,
    __standard_vector_size__,
    _clean_default_connection,
    aggregate,
    alias,
    apilevel,
    append,
    array_type,
    arrow,
    begin,
    checkpoint,
    close,
    commit,
    connect,
    cursor,
    decimal_type,
    default_connection,
    description,
    df,
    disable_profiling,
    distinct,
    dtype,
    duplicate,
    enable_profiling,
    enum_type,
    execute,
    executemany,
    extract_statements,
    fetch_arrow_table,
    fetch_df,
    fetch_df_chunk,
    fetch_record_batch,
    fetchall,
    fetchdf,
    fetchmany,
    fetchnumpy,
    fetchone,
    file_type,
    filesystem_is_registered,
    filter,
    from_arrow,
    from_csv_auto,
    from_df,
    from_parquet,
    from_query,
    get_or_create_runner,
    get_or_infer_runner_type,
    get_profiling_information,
    get_runner,
    get_table_names,
    image_type,
    install_extension,
    interrupt,
    limit,
    list_filesystems,
    list_type,
    load_extension,
    map_type,
    order,
    paramstyle,
    pl,
    project,
    query,
    query_df,
    query_progress,
    ray_cxx,
    read_csv,
    read_json,
    read_parquet,
    register,
    register_filesystem,
    remove_function,
    rollback,
    row_type,
    rowcount,
    set_default_connection,
    sql,
    sqltype,
    string_type,
    struct_type,
    table,
    table_function,
    teardown_runner,
    tensor_type,
    tf,
    threadsafety,
    to_arrow_reader,
    to_arrow_table,
    token_type,
    tokenize,
    torch,
    type,
    union_type,
    unregister,
    unregister_filesystem,
    values,
    view,
    write_csv,
)
from vane._tensor import tensor, tensor_array, tensor_data, tensor_shape
from vane._version import (
    __engine_version__,
    __version__,
    version,
)
from vane.config import VaneConfig, configure, current_config
from vane.datasink import (
    BoundDataSink,
    BoundKeyedUpsertSink,
    DataSink,
    DataSinkExecutionOptions,
    DataSinkWorker,
    DataSinkWriteError,
    EnvironmentSecret,
    WriteContext,
    WriteOutcome,
    WriteResult,
    WriteState,
    WriteSummary,
    write_datasink,
)
from vane.datasink.doris import DorisStreamLoadSink
from vane.datasink.milvus import MilvusSink
from vane.datasink.qdrant import QdrantSink
from vane.extensions import (
    DEFAULT_EXTENSION_CATALOG_URL,
    DynamicExtensionDependency,
    DynamicExtensionDescriptor,
    DynamicExtensionError,
    DynamicExtensionResolver,
    ExtensionCatalogEntry,
    ExtensionStatus,
    LocalExtensionArtifact,
    LocalExtensionProvider,
    ResolvedDynamicExtension,
    create_dynamic_extension_descriptor,
    extension_catalog,
    extension_statuses,
    load_installed_extension,
    vane_extensions,
)
from vane.value.constant import (
    BinaryValue,
    BitValue,
    BlobValue,
    BooleanValue,
    DateValue,
    DecimalValue,
    DoubleValue,
    FloatValue,
    HugeIntegerValue,
    IntegerValue,
    IntervalValue,
    ListValue,
    LongValue,
    MapValue,
    NullValue,
    ShortValue,
    StringValue,
    StructValue,
    TimestampMillisecondValue,
    TimestampNanosecondValue,
    TimestampSecondValue,
    TimestampTimeZoneValue,
    TimestampValue,
    TimeTimeZoneValue,
    TimeValue,
    UnionType,
    UnsignedBinaryValue,
    UnsignedHugeIntegerValue,
    UnsignedIntegerValue,
    UnsignedLongValue,
    UnsignedShortValue,
    UUIDValue,
    Value,
)


def use_native_media_runtime(directory: str, *, allow_distributed: bool = False) -> None:
    """Select a compatible locally rebuilt media runtime before preparing extensions.

    Set ``allow_distributed=True`` to authorize this exact runtime in Ray queries.
    Every node must separately configure VANE_NATIVE_MEDIA_RUNTIME before Ray
    starts. Start a new process to switch runtimes.
    """
    from vane._native_runtime import use_native_media_runtime as select_runtime

    select_runtime(directory, allow_distributed=allow_distributed)


def set_runner_local(
    num_workers: int | None = 1,
    *,
    max_running_tasks: _typing.Any = None,
    execution_mode: str | None = "in_process",
) -> "_Runner":
    """Configure Vane to execute through the local FTE runner."""
    from vane.runners.local import set_runner_local as _set_runner_local

    return _set_runner_local(
        num_workers,
        max_running_tasks=max_running_tasks,
        execution_mode=execution_mode,
    )


def set_runner_ray(
    address: str | None = None,
    noop_if_initialized: bool = False,
    max_task_backlog: int | None = None,
) -> "_Runner":
    """Configure Vane to execute through the Ray runner."""
    from vane.runners.ray import set_runner_ray as _set_runner_ray

    return _set_runner_ray(address, noop_if_initialized, max_task_backlog)


# Short public aliases for the native classes.
Connection = DuckDBPyConnection
Relation = DuckDBPyRelation

# Install Vane's relation conveniences after the native relation class exists.
from vane.ai import _relation_patch as _relation_patch

_VANE_SUBMODULES = frozenset(
    {
        "adbc",
        "ai",
        "datasink",
        "datasource",
        "execution",
        "experimental",
        "extensions",
        "expressions",
        "filesystem",
        "query_graph",
        "runners",
        "sqltypes",
        "udf",
        "value",
    }
)


def __getattr__(name: str) -> object:
    """Lazily expose Vane-owned public submodules."""
    if name in _VANE_SUBMODULES:
        module = _importlib.import_module(f"{__name__}.{name}")
        globals()[name] = module
        return module
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals()) | _VANE_SUBMODULES)


__all__: list[str] = [
    "read_video_frames",
    "DEFAULT_EXTENSION_CATALOG_URL",
    "AudioFile",
    "AudioFileError",
    "AudioFileFormatError",
    "AudioFileLimitError",
    "AudioMetadata",
    "BINARY",
    "BinaryValue",
    "BinderException",
    "BitValue",
    "BlobValue",
    "BooleanValue",
    "BoundDataSink",
    "BoundKeyedUpsertSink",
    "CSVLineTerminator",
    "CaseExpression",
    "CatalogException",
    "CoalesceOperator",
    "ColumnExpression",
    "Connection",
    "ConnectionException",
    "ConstantExpression",
    "ConstraintException",
    "ConversionException",
    "DataError",
    "DataSink",
    "DataSinkExecutionOptions",
    "DataSinkWorker",
    "DataSinkWriteError",
    "DatabaseError",
    "DATETIME",
    "DateValue",
    "DecimalValue",
    "DefaultExpression",
    "DependencyException",
    "DBAPITypeObject",
    "DoubleValue",
    "DorisStreamLoadSink",
    "DynamicExtensionDependency",
    "DynamicExtensionDescriptor",
    "DynamicExtensionError",
    "DynamicExtensionResolver",
    "DuckDBPyConnection",
    "DuckDBPyRelation",
    "EnvRegistry",
    "EnvironmentSecret",
    "Error",
    "ExtensionCatalogEntry",
    "ExtensionStatus",
    "ExpectedResultType",
    "ExplainType",
    "Expression",
    "FatalException",
    "File",
    "FileStat",
    "FloatValue",
    "FunctionExpression",
    "HTTPException",
    "HugeIntegerValue",
    "IOException",
    "Image",
    "ImageFormat",
    "ImageMode",
    "ImageProperty",
    "ImageFile",
    "ImageFileError",
    "ImageFileFormatError",
    "ImageFileLimitError",
    "ImageMetadata",
    "IntegerValue",
    "IntegrityError",
    "InternalError",
    "InternalException",
    "InterruptException",
    "IntervalValue",
    "InvalidInputException",
    "InvalidTypeException",
    "LambdaExpression",
    "ListValue",
    "LongValue",
    "LocalExtensionArtifact",
    "LocalExtensionProvider",
    "MapValue",
    "MediaType",
    "MilvusSink",
    "QdrantSink",
    "NUMBER",
    "NotImplementedException",
    "NotSupportedError",
    "NullValue",
    "OperationalError",
    "OutOfMemoryException",
    "OutOfRangeException",
    "ParserException",
    "PermissionException",
    "ProgrammingError",
    "PythonExceptionHandling",
    "RenderMode",
    "Relation",
    "ResolvedDynamicExtension",
    "ROWID",
    "SQLExpression",
    "SequenceException",
    "SerializationException",
    "ShortValue",
    "StarExpression",
    "Statement",
    "StatementType",
    "STRING",
    "StringValue",
    "StructValue",
    "SyntaxException",
    "TimeTimeZoneValue",
    "TimeValue",
    "TimestampMillisecondValue",
    "TimestampNanosecondValue",
    "TimestampSecondValue",
    "TimestampTimeZoneValue",
    "TimestampValue",
    "TransactionException",
    "TypeMismatchException",
    "UUIDValue",
    "UnionType",
    "UnsignedBinaryValue",
    "UnsignedHugeIntegerValue",
    "UnsignedIntegerValue",
    "UnsignedLongValue",
    "UnsignedShortValue",
    "Value",
    "VideoFile",
    "VideoFileError",
    "VideoFileFormatError",
    "VideoFileLimitError",
    "VideoFrameData",
    "VideoMetadata",
    "VaneFileReader",
    "Warning",
    "WriteContext",
    "WriteOutcome",
    "WriteResult",
    "WriteState",
    "WriteSummary",
    "__formatted_python_version__",
    "__git_revision__",
    "__interactive__",
    "__jupyter__",
    "__standard_vector_size__",
    "__engine_version__",
    "__version__",
    "_clean_default_connection",
    "aggregate",
    "alias",
    "apilevel",
    "append",
    "audio_file",
    "audio_metadata",
    "resample",
    "array_type",
    "arrow",
    "begin",
    "checkpoint",
    "close",
    "commit",
    "connect",
    "configure",
    "create_dynamic_extension_descriptor",
    "current_config",
    "cursor",
    "decimal_type",
    "decode_image",
    "image_hash",
    "decode_image_file",
    "default_connection",
    "description",
    "df",
    "disable_profiling",
    "distinct",
    "dtype",
    "duplicate",
    "enable_profiling",
    "enum_type",
    "execute",
    "executemany",
    "extension_catalog",
    "extension_statuses",
    "extract_statements",
    "fetch_arrow_table",
    "fetch_df",
    "fetch_df_chunk",
    "fetch_record_batch",
    "fetchall",
    "fetchdf",
    "fetchmany",
    "fetchnumpy",
    "fetchone",
    "file",
    "file_content_id",
    "file_enrich",
    "file_exists",
    "file_locator_id",
    "file_mime_type",
    "file_path",
    "file_same_content",
    "file_same_location",
    "file_size",
    "file_stat",
    "file_type",
    "filesystem_is_registered",
    "filter",
    "from_arrow",
    "from_csv_auto",
    "from_df",
    "from_files",
    "from_parquet",
    "from_query",
    "get_or_create_runner",
    "get_or_infer_runner_type",
    "get_profiling_information",
    "get_runner",
    "get_table_names",
    "guess_mime_type",
    "image_file",
    "image_file_metadata",
    "image_type",
    "image_attribute",
    "crop",
    "encode_image",
    "resize",
    "convert_image",
    "image_channel",
    "image_height",
    "image_mode",
    "image_to_tensor",
    "image_width",
    "install_extension",
    "interrupt",
    "limit",
    "list_files",
    "list_filesystems",
    "list_type",
    "load_extension",
    "load_installed_extension",
    "map_type",
    "order",
    "open_file",
    "paramstyle",
    "pl",
    "project",
    "query",
    "query_df",
    "query_progress",
    "ray_cxx",
    "read_csv",
    "read_json",
    "read_parquet",
    "register",
    "register_filesystem",
    "remove_function",
    "rollback",
    "row_type",
    "rowcount",
    "set_default_connection",
    "use_native_media_runtime",
    "set_runner_local",
    "set_runner_ray",
    "sql",
    "sqltype",
    "string_type",
    "struct_type",
    "table",
    "table_function",
    "teardown_runner",
    "tensor_type",
    "tensor",
    "tensor_array",
    "tensor_data",
    "tensor_shape",
    "tf",
    "threadsafety",
    "to_arrow_reader",
    "to_arrow_table",
    "token_type",
    "tokenize",
    "to_file",
    "torch",
    "type",
    "try_to_file",
    "video_file",
    "video_metadata",
    "build_video_index",
    "video_index_info",
    "video_scan_stats",
    "video_frames",
    "video_keyframes",
    "get_video_frame_by_idx",
    "union_type",
    "unregister",
    "unregister_filesystem",
    "vane_extensions",
    "values",
    "view",
    "version",
    "write_csv",
    "write_datasink",
    "VaneConfig",
    "attach_function",
    "cls",
    "col",
    "detach_function",
    "env",
    "func",
    "lit",
    "sql_expr",
]
