#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

"""Check or add SPDX headers according to Vane's source provenance policy."""

from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]

SOURCE_SUFFIXES = {
    ".bash",
    ".c",
    ".cc",
    ".cmake",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".hxx",
    ".ipp",
    ".java",
    ".py",
    ".pyi",
    ".rs",
    ".sh",
}
SOURCE_NAMES = {"CMakeLists.txt", "Dockerfile", "Makefile"}
ROOT_SOURCE_NAMES = SOURCE_NAMES | {"format"}

GENERATED_MARKERS = (
    "this file is automatically generated",
    "this code is automatically generated",
    "do not edit this file manually",
    "do not make any changes directly here",
)
VALID_SPDX_LICENSE_LINE = re.compile(r"^(?:#|//) SPDX-License-Identifier: \S.*$", re.MULTILINE)


@dataclass(frozen=True)
class RepositoryPolicy:
    name: str
    path: Path
    baseline: str
    source_names: frozenset[str]
    excluded_prefixes: tuple[str, ...]
    exclude_nested_third_party: bool
    new_license: str
    modified_license: str
    non_duckdb_modified_prefixes: tuple[str, ...]
    duckdb_derived_additions: frozenset[str]


POLICIES = {
    "root": RepositoryPolicy(
        name="root",
        path=REPOSITORY_ROOT,
        baseline="60d1d025be5040469662a40d6c0148916a28175a",
        source_names=frozenset(ROOT_SOURCE_NAMES),
        excluded_prefixes=("external/duckdb/", "third_party/", "vcpkg/", "vane/experimental/spark/"),
        exclude_nested_third_party=False,
        new_license="Apache-2.0",
        modified_license="MIT AND Apache-2.0",
        non_duckdb_modified_prefixes=("vane_adbc_driver_duckdb/",),
        duckdb_derived_additions=frozenset({"vane/_duckdb_func.py"}),
    ),
    "duckdb": RepositoryPolicy(
        name="duckdb",
        path=REPOSITORY_ROOT / "external" / "duckdb",
        # Monorepo snapshot that imported upstream DuckDB commit
        # 3a3967aa8190d0a2d1931d4ca4f5d920760030b4 under external/duckdb.
        baseline="c143c16b541e6175c5070f41f6bfcfe17b5bcacd",
        source_names=frozenset(SOURCE_NAMES),
        excluded_prefixes=("third_party/", "vcpkg/"),
        exclude_nested_third_party=True,
        new_license="MIT",
        modified_license="MIT",
        non_duckdb_modified_prefixes=(),
        duckdb_derived_additions=frozenset(),
    ),
}


def git_output(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", "-C", str(repo), *args], text=True)


def changed_source_files(policy: RepositoryPolicy) -> list[tuple[str, str]]:
    output = git_output(
        policy.path,
        "diff",
        "--relative",
        "--name-status",
        "--find-renames",
        policy.baseline,
        "--",
        ".",
    )
    result: list[tuple[str, str]] = []
    for line in output.splitlines():
        fields = line.split("\t")
        if len(fields) == 2 and fields[0] in {"A", "M"}:
            status, relative_path = fields
        elif len(fields) == 3 and fields[0].startswith(("R", "C")):
            status, relative_path = "M", fields[2]
        else:
            continue
        path = Path(relative_path)
        if path.suffix not in SOURCE_SUFFIXES and path.name not in policy.source_names:
            continue
        result.append((status, relative_path))

    known_paths = {relative_path for _, relative_path in result}
    untracked = git_output(policy.path, "ls-files", "--others", "--exclude-standard", "--", ".")
    for relative_path in untracked.splitlines():
        path = Path(relative_path)
        if relative_path in known_paths:
            continue
        if path.suffix not in SOURCE_SUFFIXES and path.name not in policy.source_names:
            continue
        result.append(("A", relative_path))
    return result


def is_excluded(policy: RepositoryPolicy, relative_path: str, text: str) -> bool:
    if relative_path.startswith(policy.excluded_prefixes):
        return True
    if policy.exclude_nested_third_party and "/third_party/" in f"/{relative_path}":
        return True
    if relative_path.startswith("scripts/"):
        return False
    prefix = text[:4096].lower()
    return any(marker in prefix for marker in GENERATED_MARKERS)


def comment_prefix(path: Path) -> str:
    if path.suffix in {".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx", ".ipp", ".java", ".rs"}:
        return "//"
    return "#"


def is_cmake_source(path: Path) -> bool:
    return path.suffix == ".cmake" or path.name == "CMakeLists.txt"


def license_header(policy: RepositoryPolicy, status: str, relative_path: str, path: Path) -> str:
    prefix = comment_prefix(path)
    inherited_duckdb_source = status == "M"
    if relative_path.startswith(policy.non_duckdb_modified_prefixes):
        inherited_duckdb_source = False
    if relative_path in policy.duckdb_derived_additions:
        inherited_duckdb_source = True
    license_expression = policy.modified_license if inherited_duckdb_source else policy.new_license
    metadata: list[str] = []
    if inherited_duckdb_source:
        metadata.append(f"{prefix} SPDX-FileCopyrightText: 2018-2025 Stichting DuckDB Foundation")
    metadata.append(f"{prefix} SPDX-FileCopyrightText: 2026 Vane contributors")
    metadata.append(f"{prefix} SPDX-License-Identifier: {license_expression}")
    if is_cmake_source(path):
        lines = [item for line in metadata for item in (line, prefix)]
        lines.pop()
    else:
        lines = metadata
    if inherited_duckdb_source:
        lines.extend((prefix, f"{prefix} Modified by Vane contributors."))
    return "\n".join(lines) + "\n\n"


def add_header(path: Path, header: str) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    if not lines:
        path.write_text(header.rstrip("\n") + "\n", encoding="utf-8")
        return
    insertion_index = 0
    if lines and lines[0].startswith("#!"):
        insertion_index = 1
    if insertion_index < len(lines) and re.search(r"coding[:=]\s*[-\w.]+", lines[insertion_index]):
        insertion_index += 1
    lines.insert(insertion_index, header)
    path.write_text("".join(lines), encoding="utf-8")


def remove_malformed_cmake_header(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    if not lines or "SPDX-License-Identifier:" not in "".join(lines[:8]):
        return
    for index, line in enumerate(lines):
        if not line.strip():
            path.write_text("".join(lines[index + 1 :]), encoding="utf-8")
            return


def process(policy: RepositoryPolicy, *, fix: bool) -> tuple[int, int, int]:
    missing: list[tuple[str, str, Path, str, bool]] = []
    excluded = 0
    existing = 0
    for status, relative_path in changed_source_files(policy):
        path = policy.path / relative_path
        text = path.read_text(encoding="utf-8")
        if is_excluded(policy, relative_path, text):
            excluded += 1
            continue
        if VALID_SPDX_LICENSE_LINE.search(text[:4096]):
            existing += 1
            continue
        malformed_cmake_header = is_cmake_source(path) and "SPDX-License-Identifier:" in text[:4096]
        missing.append(
            (status, relative_path, path, license_header(policy, status, relative_path, path), malformed_cmake_header)
        )

    if fix:
        for _, _, path, header, malformed_cmake_header in missing:
            if malformed_cmake_header:
                remove_malformed_cmake_header(path)
            add_header(path, header)
    elif missing:
        print(f"{policy.name}: {len(missing)} source files are missing SPDX headers:")
        for status, relative_path, _, _, _ in missing:
            print(f"  {status} {relative_path}")

    action = "updated" if fix else "missing"
    print(f"{policy.name}: {action}={len(missing)} existing={existing} excluded={excluded}")
    return len(missing), existing, excluded


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fix", action="store_true", help="Add missing headers in place")
    parser.add_argument("--repo", choices=("all", "root", "duckdb"), default="all")
    args = parser.parse_args()

    selected = POLICIES.values() if args.repo == "all" else (POLICIES[args.repo],)
    missing = 0
    for policy in selected:
        policy_missing, _, _ = process(policy, fix=args.fix)
        missing += policy_missing
    return 0 if args.fix or missing == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
