#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

"""Create the license bundle for native libraries linked into Vane wheels."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SHARE_DIR = REPOSITORY_ROOT / "vcpkg_installed" / "x64-linux" / "share"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "LICENSES" / "vcpkg-binary-dependencies.txt"


def _baseline() -> str:
    manifest = json.loads((REPOSITORY_ROOT / "vcpkg.json").read_text(encoding="utf-8"))
    return str(manifest["builtin-baseline"])


def render_bundle(share_dir: Path) -> str:
    """Render every installed vcpkg copyright record in stable order."""
    records = sorted(
        (path for path in share_dir.glob("*/copyright") if not path.parent.name.startswith("vcpkg-")),
        key=lambda path: path.parent.name,
    )
    if not records:
        raise FileNotFoundError(f"no vcpkg copyright records found below {share_dir}")

    lines = [
        "Vane native binary dependency licenses",
        "=======================================",
        "",
        "Generated from vcpkg installed copyright records.",
        "vcpkg helper ports used only by the build are intentionally excluded.",
        f"vcpkg builtin baseline: {_baseline()}",
        "Do not edit this file manually; run scripts/sync_vcpkg_licenses.py.",
        "",
    ]
    for record in records:
        component = record.parent.name
        content = record.read_text(encoding="utf-8", errors="replace").strip()
        lines.extend(
            (
                "=" * 80,
                f"Component: {component}",
                f"Source record: share/{component}/copyright",
                "=" * 80,
                content,
                "",
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--share-dir", type=Path, default=DEFAULT_SHARE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail instead of rewriting an out-of-date bundle")
    args = parser.parse_args()

    expected = render_bundle(args.share_dir)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if actual != expected:
            print(f"{args.output} is missing or out of date")
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
