# SPDX-FileCopyrightText: 2018-2025 Stichting DuckDB Foundation
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: MIT AND Apache-2.0
#
# Modified by Vane contributors.

import typing

__all__: list[str] = ["ARROW", "DEFAULT", "NATIVE", "SPECIAL", "FunctionNullHandling", "PythonUDFType"]

class FunctionNullHandling:
    DEFAULT: typing.ClassVar[FunctionNullHandling]  # value = <FunctionNullHandling.DEFAULT: 0>
    SPECIAL: typing.ClassVar[FunctionNullHandling]  # value = <FunctionNullHandling.SPECIAL: 1>
    __members__: typing.ClassVar[
        dict[str, FunctionNullHandling]
    ]  # value = {'DEFAULT': <FunctionNullHandling.DEFAULT: 0>, 'SPECIAL': <FunctionNullHandling.SPECIAL: 1>}
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PythonUDFType:
    ARROW: typing.ClassVar[PythonUDFType]  # value = <PythonUDFType.ARROW: 1>
    NATIVE: typing.ClassVar[PythonUDFType]  # value = <PythonUDFType.NATIVE: 0>
    __members__: typing.ClassVar[
        dict[str, PythonUDFType]
    ]  # value = {'NATIVE': <PythonUDFType.NATIVE: 0>, 'ARROW': <PythonUDFType.ARROW: 1>}
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

ARROW: PythonUDFType  # value = <PythonUDFType.ARROW: 1>
DEFAULT: FunctionNullHandling  # value = <FunctionNullHandling.DEFAULT: 0>
NATIVE: PythonUDFType  # value = <PythonUDFType.NATIVE: 0>
SPECIAL: FunctionNullHandling  # value = <FunctionNullHandling.SPECIAL: 1>
