# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

from typing import Any

def check_entry() -> None: ...

class StoreGuard:
    @staticmethod
    def acquire(path: str, exclusive: bool, create: bool) -> StoreGuard | None: ...
    def close(self) -> None: ...

class MaterializedIO:
    @staticmethod
    def staging_bytes(frame_bytes: int) -> int: ...
    @staticmethod
    def write(path: str, channel: DirectChannel, consumer: str, max_bytes: int, staging: int) -> MaterializedIO: ...
    @staticmethod
    def read(
        path: str, channel: DirectChannel, producer: str, max_bytes: int, staging: int, expected: dict[str, Any]
    ) -> MaterializedIO: ...
    @staticmethod
    def verify(path: str, expected: dict[str, Any], schema: bytes) -> None: ...
    def status(self) -> dict[str, Any]: ...
    def cancel(self, reason: str) -> None: ...
    def close(self) -> None: ...

class DirectLimits:
    def __init__(self, window_bytes: int, frame_bytes: int, frame_rows: int, frame_slots: int) -> None: ...

class _TestSignal:
    def __init__(self) -> None: ...
    @property
    def count(self) -> int: ...

class DirectBatch:
    producer: str
    sequence: int
    @property
    def num_rows(self) -> int: ...
    def to_rows(self) -> list[tuple[Any, ...]]: ...
    def to_arrow(self, names: list[str]) -> Any: ...
    def slice(self, offset: int, count: int) -> DirectBatch: ...
    def close(self) -> None: ...

class DirectChannel:
    def __init__(self, schema: bytes, limits: DirectLimits, producers: int, consumers: list[str]) -> None: ...
    def add_producer(self, producer: str) -> None: ...
    def seal_producers(self) -> None: ...
    def finish(self, producer: str, sequence: int) -> None: ...
    def abort(self, reason: str) -> None: ...
    def close_consumer(self, consumer: str) -> None: ...
    def poll(self, consumer: str, signal: _TestSignal | None = None) -> tuple[str, DirectBatch | None]: ...
    def _write_rows(
        self, producer: str, sequence: int, rows: list[tuple[Any, ...]], signal: _TestSignal | None = None
    ) -> str: ...
    def snapshot(self) -> dict[str, Any]: ...
    def producer_drained(self, producer: str) -> bool: ...

class TaskService:
    def __init__(self, connection: Any) -> None: ...
    def prepare(
        self,
        task_id: str,
        payload: bytes,
        connection_snapshot: bytes,
        source_snapshot: bytes,
        assignments: dict[str, list[str]],
        inputs: dict[str, list[tuple[DirectChannel, str]]],
        outputs: list[dict[str, Any]],
    ) -> None: ...
    def start(self, task_id: str, token: str) -> None: ...
    def pump(self, steps: int) -> int: ...
    def cancel(self, reason: str) -> None: ...
    def expire(self) -> bool: ...
    def release(self) -> None: ...
    def status(self) -> list[dict[str, Any]]: ...
    def production_status(self) -> dict[str, Any]: ...
    def diagnostics(self) -> list[dict[str, Any]]: ...

def arrow_schema(schema: bytes, names: list[str]) -> Any: ...

class DirectFlight:
    def __init__(
        self,
        host: str,
        advertise: str,
        links: int,
        staging: int,
        frame: int,
        port: int = 0,
        certificate: str = "",
        private_key: str = "",
    ) -> None: ...
    @property
    def location(self) -> str: ...
    @property
    def error(self) -> str: ...
    @property
    def active_links(self) -> int: ...
    @property
    def ready(self) -> bool: ...
    @staticmethod
    def staging_per_link(frame_bytes: int) -> int: ...
    def publish(self, ticket: str, channel: DirectChannel, consumer: str) -> None: ...
    def subscribe(
        self,
        location: str,
        ticket: str,
        channel: DirectChannel,
        producer: str,
        timeout: float,
        root_certificates: str = "",
    ) -> None: ...
    def revoke(self, ticket: str) -> None: ...
    def delivered(self, ticket: str) -> bool: ...
    def cancel(self, reason: str) -> None: ...
    def close(self) -> None: ...
