# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Iterable, Mapping, Sequence
from typing import Any, SupportsFloat, SupportsIndex, SupportsInt, overload

from typing_extensions import Never, Self

from vane._native import DuckDBPyRelation

class DistributedPhysicalPlan:
    def __init__(self, _token: Never) -> None: ...
    def idx(self) -> str: ...
    def resource_query_id(self) -> str: ...
    def session_id(self) -> str: ...
    def session_config(self) -> dict[str, str]: ...
    def has_explicit_s3_credentials(self) -> bool: ...
    def has_root(self) -> bool: ...
    def clone(self, conn: object | None = ...) -> DistributedPhysicalPlan: ...
    def num_partitions(self) -> int: ...
    def repr_ascii(self, show_cardinality: bool, /) -> str: ...
    def repr_mermaid(self, show_cardinality: bool, show_types: bool, /) -> str: ...
    def scan_task_descriptor_map(self) -> dict[str, list[bytes]]: ...
    def collect_query_resource_graph_metadata(self, conn: object | None = ...) -> dict[str, Any]: ...
    def collect_udf_nodes(self, conn: object | None = ...) -> list[dict[str, Any]]: ...
    def collect_vllm_nodes(self, conn: object | None = ...) -> list[dict[str, Any]]: ...
    def set_udf_actor_handles(self, handles_map: dict[Any, Any], conn: object | None = ...) -> None: ...
    def _validate_serializable_for_submission(self) -> None: ...

class ResultPartitionStream:
    def __init__(self, _token: Never) -> None: ...
    def blocking_next(self) -> object: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> object: ...

class DistributedPhysicalPlanRunner:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, backend: object) -> None: ...
    def run_plan(self, plan: DistributedPhysicalPlan, conn: object | None = ...) -> ResultPartitionStream: ...
    def run_copy_plan(self, plan: DistributedPhysicalPlan, conn: object | None = ...) -> dict[str, Any]: ...
    def finalize_copy(
        self,
        file_infos: list[Any],
        copy_spec: str,
        staging_root: str,
        conn: object | None = ...,
    ) -> dict[str, Any]: ...
    def execute_native(
        self,
        conn: object,
        plan: DistributedPhysicalPlan,
        scan_task: object | None = ...,
        exchange_source_task: object | None = ...,
        copy_output_info: object | None = ...,
        exchange_sink_instance: object | None = ...,
        fte_scan_source_queues: object | None = ...,
        fte_exchange_source_queues: object | None = ...,
        dynamic_filter_domains: object | None = ...,
        native_progress_callback: object | None = ...,
        runtime_context: object | None = ...,
        effective_session_config: object | None = ...,
        snapshot_secrets_prepared: bool = ...,
    ) -> NativeDistributedTaskResult: ...
    def drop_query_fragments(self, query_id: str) -> None: ...
    def close_session(self, session_id: str) -> None: ...
    def warm_up(self) -> None: ...
    def shutdown(self) -> None: ...
    def fragment_stats(self) -> dict[str, Any]: ...

class FteSplitQueue:
    def __init__(self) -> None: ...
    def add_scan_split(self, bytes: bytes) -> None: ...
    def add_exchange_source_split(self, bytes: bytes) -> None: ...
    def no_more_splits(self) -> None: ...
    def cancel(self) -> None: ...
    def complete_consumed_splits(self) -> None: ...
    def buffered_splits(self) -> int: ...
    def buffered_bytes(self) -> int: ...
    def submitted_splits(self) -> int: ...
    def consumed_splits(self) -> int: ...
    def completed_splits(self) -> int: ...
    def submitted_rows(self) -> int: ...
    def submitted_input_bytes(self) -> int: ...
    def consumed_rows(self) -> int: ...
    def consumed_input_bytes(self) -> int: ...
    def completed_rows(self) -> int: ...
    def completed_input_bytes(self) -> int: ...
    def queue_wait_ms(self) -> int: ...
    def exchange_source_partition_count(self) -> int: ...
    def exchange_source_task_count(self) -> int: ...
    def try_get_next(self) -> dict[str, Any]: ...
    def wait_for_next(self) -> dict[str, Any]: ...

class NativePartitionMetadata:
    def __init__(
        self,
        num_rows: SupportsInt | SupportsIndex,
        size_bytes: SupportsInt | SupportsIndex,
        /,
    ) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...

class NativeDistributedTaskResult:
    def __init__(
        self,
        partition_payloads: Iterable[object],
        partition_metadatas: Iterable[NativePartitionMetadata],
        result_schema: Mapping[str, Any] | None,
        stats: Iterable[int],
        completion_status: str,
        flight_port: SupportsInt | SupportsIndex = ...,
        exchange_sink_instance: object | None = ...,
        task_stats: object | None = ...,
    ) -> None: ...
    @property
    def partition_payloads(self) -> list[object]: ...
    @property
    def partition_metadatas(self) -> list[NativePartitionMetadata]: ...
    @property
    def result_schema(self) -> Mapping[str, Any] | None: ...
    @property
    def stats(self) -> Iterable[int]: ...
    @property
    def task_stats(self) -> object: ...
    @property
    def completion_status(self) -> str: ...
    @property
    def flight_port(self) -> int: ...
    @property
    def exchange_sink_instance(self) -> object: ...

class PyLogicalPlan:
    def __init__(self, _token: Never) -> None: ...
    @staticmethod
    def from_duckdb_relation(relation: DuckDBPyRelation, query_id: object, /) -> PyLogicalPlan: ...
    def idx(self) -> str: ...
    def session_id(self) -> str: ...
    def session_config(self) -> dict[str, str]: ...
    def has_explicit_s3_credentials(self) -> bool: ...
    def to_physical_plan(
        self,
        conn: object | None = ...,
        effective_session_config: object | None = ...,
    ) -> DistributedPhysicalPlan: ...

class RayResultPartitionRef:
    def __init__(
        self,
        object_ref: object,
        num_rows: SupportsInt | SupportsIndex,
        size_bytes: SupportsInt | SupportsIndex,
        lease_owner: object,
        /,
    ) -> None: ...
    @property
    def object_ref(self) -> object: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def size_bytes(self) -> int: ...
    @property
    def lease_owner(self) -> object: ...

class RayTaskResult:
    def __init__(self, _token: Never) -> None: ...
    @staticmethod
    def success(
        ray_part_refs: Sequence[object],
        stats: Sequence[SupportsInt | SupportsIndex],
        result_schema: object | None = ...,
        flight_port: SupportsInt | SupportsIndex = ...,
        exchange_sink_instance: object | None = ...,
    ) -> RayTaskResult: ...
    @staticmethod
    def no_output() -> RayTaskResult: ...
    @staticmethod
    def update_ack() -> RayTaskResult: ...
    @staticmethod
    def worker_died() -> RayTaskResult: ...
    @staticmethod
    def worker_unavailable() -> RayTaskResult: ...
    @property
    def ok(self) -> bool: ...
    @property
    def has_output(self) -> bool: ...
    @property
    def result_schema(self) -> object: ...
    @property
    def flight_port(self) -> int: ...
    @property
    def exchange_sink_instance(self) -> object: ...

class RayWorkerRuntime:
    def __init__(
        self,
        worker_id: str,
        actor_handle: object,
        num_cpus: SupportsFloat | SupportsIndex,
        num_gpus: SupportsFloat | SupportsIndex,
        total_memory_bytes: SupportsInt | SupportsIndex,
        /,
    ) -> None: ...
    @property
    def worker_id(self) -> str: ...
    @property
    def num_cpus(self) -> float: ...
    @property
    def num_gpus(self) -> float: ...
    @property
    def total_memory_bytes(self) -> int: ...

class RayWorkerTask:
    def __init__(self, _token: Never) -> None: ...
    def context(self) -> dict[str, str]: ...
    def task_context(self) -> dict[str, Any]: ...
    def name(self) -> str: ...
    def plan(self) -> DistributedPhysicalPlan | None: ...
    def exchange_sink_instance(self) -> dict[str, Any] | None: ...
    def Inputs(self) -> dict[str, dict[str, object]]: ...

class RayWorkerManager:
    def __init__(self) -> None: ...
    def worker_snapshots(self) -> list[dict[str, Any]]: ...
    def shutdown(self) -> None: ...
    def drop_query_fragments(self, query_id: str) -> None: ...
    def wait_fte_query(self, query_id: str, timeout_s: SupportsFloat | SupportsIndex = ...) -> None: ...
    def fragment_stats(self) -> dict[str, Any]: ...
    def try_autoscale(self, bundles: object, /) -> None: ...

def _register_query_python_replay_state(query_id: str, plan: DistributedPhysicalPlan) -> bool: ...
def _lookup_query_connection_snapshot(query_id: str) -> Mapping[str, Any] | None: ...
def _resolve_query_snapshot_connection(connection: object, query_id: str) -> object: ...
def _prepare_query_secret_snapshot(
    connection: object,
    query_id: str,
    include_snapshot_secrets: bool = ...,
) -> None: ...
def _cleanup_query_python_replay_state(query_id: str) -> None: ...
def begin_flight_shuffle_query_execution(query_id: str) -> None: ...
def end_flight_shuffle_query_execution(query_id: str) -> None: ...
def cleanup_flight_shuffle_for_query(
    query_id: str,
    cleanup_connection: object | None = ...,
    connection_snapshot_query_id: str = ...,
    apply_snapshot_s3_credentials: bool = ...,
    effective_session_config: object | None = ...,
    snapshot_secrets_prepared: bool = ...,
) -> dict[str, int | str]: ...
def close_flight_shuffle_query(query_id: str) -> None: ...
def flight_shuffle_query_status(query_id: str) -> dict[str, Any]: ...
def retire_flight_shuffle_query(query_id: str) -> None: ...
def shutdown_local_flight_service() -> None: ...
def describe_native_progress(conn: object, plan: DistributedPhysicalPlan) -> dict[str, Any]: ...
def merge_scan_task_descriptors(bytes_list: list[bytes]) -> bytes: ...
def exchange_source_task_logical_identity(bytes: bytes) -> dict[str, Any]: ...
def exchange_source_task_partition_indices(bytes: bytes) -> list[int]: ...
def exchange_source_task_replicated(bytes: bytes) -> bool: ...
def scan_task_source_partition_id(bytes: bytes) -> int: ...
def split_exchange_source_task_by_partition(bytes: bytes) -> list[tuple[int, bytes, int, int, bool]]: ...
def cleanup_expired_copy_direct_write_runs(
    base_path: str,
    min_age_ms: SupportsInt | SupportsIndex,
    now_epoch_ms: SupportsInt | SupportsIndex = ...,
    conn: object | None = ...,
) -> dict[str, Any]: ...
def read_committed_copy_direct_write_result(
    base_path: str, run_id: str, conn: object | None = ...
) -> dict[str, Any]: ...
def inspect_copy_direct_write_run(base_path: str, run_id: str, conn: object | None = ...) -> dict[str, Any]: ...
def force_abort_copy_direct_write_run(base_path: str, run_id: str, conn: object | None = ...) -> dict[str, Any]: ...
def register_copy_direct_write_run_lifecycle(
    base_path: str, run_id: str, created_epoch_ms: SupportsInt | SupportsIndex = ...
) -> dict[str, Any]: ...
def cleanup_uncommitted_copy_direct_write_run(base_path: str, run_id: str) -> dict[str, Any]: ...
